name '3fs-ffmpeg'
version '0.0.1'
source 'https://github.com/3fs/puppet-ffmpeg'
author '3fs'
license 'MIT License'
summary 'Simple puppet module that installs ffmpeg.'
description 'Simple puppet module that installs ffmpeg.'
project_page 'https://github.com/3fs/puppet-ffmpeg'
